/**
 * @file g_params.c
 * @brief G-Parameter Implementation — Inverse Hybrid Two-Port Analysis
 *
 * G-parameters are the natural representation for FET amplifiers,
 * mixing input admittance with output impedance. They are the dual
 * of H-parameters (G = H⁻¹).
 */

#include "../include/g_params.h"
#include <float.h>

/* ============================================================================
 * L1: G-parameter Creation
 * ============================================================================ */

matrix2x2_t gparams_create(complex_t g11, complex_t g12,
                            complex_t g21, complex_t g22) {
    return matrix2x2_make(g11, g12, g21, g22);
}

/**
 * Common-source FET G-parameters.
 *
 * At DC:
 *   g11 = 1/RG ≈ 0 (ideal gate: open circuit, zero input admittance)
 *   g12 = 0 (no reverse current transfer in simplified model)
 *   g21 = -gm * ro (intrinsic voltage gain, negative for inversion)
 *   g22 = ro (output resistance)
 *
 * Intrinsic gain gm*ro is a fundamental technology parameter.
 * It determines the maximum single-stage voltage gain with an
 * ideal current-source load.
 *
 * In modern CMOS:
 *   180nm: gm*ro ≈ 20-40
 *   65nm:  gm*ro ≈ 10-20
 *   28nm:  gm*ro ≈ 5-15
 *   5nm:   gm*ro ≈ 3-8
 *
 * The degradation is due to channel-length modulation in short channels.
 *
 * Course: Berkeley EE140 — MOS intrinsic gain
 */
matrix2x2_t gparams_fet_cs(double gm, double ro, double rg) {
    double g11_val = (rg > 1e-30) ? 1.0 / rg : 0.0;
    return matrix2x2_make(
        complex_make(g11_val, 0.0),      /* g11: input admittance = 1/RG */
        complex_make(0.0, 0.0),          /* g12: reverse current ≈ 0 */
        complex_make(-gm * ro, 0.0),     /* g21: intrinsic gain = -gm*ro */
        complex_make(ro, 0.0)            /* g22: output resistance */
    );
}

/**
 * Common-gate FET G-parameters.
 *
 * CG stage:
 *   Input at source → low impedance (≈ 1/gm)
 *   Output at drain → high impedance (≈ ro, boosted by body effect)
 *   Non-inverting gain (Vout/Vin > 0)
 *
 *   g11 = gm + gmb + 1/ro ≈ gm (input admittance, low Zin)
 *   g21 = (gm + gmb) * ro (voltage gain, positive)
 *   g22 ≈ ro (output resistance, degenerated by source)
 *
 * The CG stage is the FET equivalent of the BJT common-base.
 * Advantages: wide bandwidth (no Miller effect), good isolation.
 * Used in: cascode amplifiers, current buffers, TIA input stages.
 *
 * Course: Stanford EE214 — Common-gate stage
 */
matrix2x2_t gparams_fet_cg(double gm, double ro, double rs) {
    /* Input admittance at source: ~gm (looking into source of a CG FET) */
    double g11_val = gm;
    /* Voltage gain: gm * (ro || rs_load) */
    double g21_val = gm * ro;
    /* Output impedance: ro + (1 + gm*ro) * rs (degeneration) */
    double g22_val = ro + (1.0 + gm * ro) * rs;

    return matrix2x2_make(
        complex_make(g11_val, 0.0),
        complex_make(0.0, 0.0),
        complex_make(g21_val, 0.0),
        complex_make(g22_val, 0.0)
    );
}

/**
 * Common-drain (source follower) FET G-parameters.
 *
 *   g11 ≈ 0 (gate input, very high impedance)
 *   g21 = gm*rs / (1 + gm*rs) (voltage gain, close to 1)
 *   g22 = 1/gm || rs (output impedance, low → good for driving loads)
 *
 * The source follower is the FET equivalent of the BJT emitter follower.
 * Key benefit: low output impedance ≈ 1/gm (typically 50-200Ω).
 * Voltage gain slightly less than 1 due to body effect.
 */
matrix2x2_t gparams_fet_cd(double gm, double rg, double rs) {
    double g11_val = (rg > 1e-30) ? 1.0 / rg : 0.0;
    double g21_val = (gm * rs) / (1.0 + gm * rs);
    double g22_val = 1.0 / gm;
    if (rs > 1e-30) {
        g22_val = (1.0 / gm) * rs / ((1.0 / gm) + rs);
    }

    return matrix2x2_make(
        complex_make(g11_val, 0.0),
        complex_make(0.0, 0.0),
        complex_make(g21_val, 0.0),
        complex_make(g22_val, 0.0)
    );
}

/* ============================================================================
 * L3: G-parameter Analysis
 * ============================================================================ */

/**
 * Voltage gain: Av = g21 * ZL / (g22 + ZL).
 *
 * For CS FET with ZL << ro: Av ≈ g21 * ZL / ro = -gm * ZL.
 * This is the classic CS gain formula: -gm * (ro || ZL) = -gm*ZL for small ZL.
 */
complex_t gparams_voltage_gain(matrix2x2_t g, complex_t zl) {
    complex_t num = complex_mul(g.m21, zl);
    complex_t denom = complex_add(g.m22, zl);
    return complex_div(num, denom);
}

complex_t gparams_input_admittance(matrix2x2_t g, complex_t zl) {
    complex_t denom = complex_add(g.m22, zl);
    complex_t term = complex_div(complex_mul(g.m12, g.m21), denom);
    return complex_sub(g.m11, term);
}

complex_t gparams_output_impedance(matrix2x2_t g, complex_t ys) {
    complex_t denom = complex_add(g.m11, ys);
    complex_t term = complex_div(complex_mul(g.m12, g.m21), denom);
    return complex_sub(g.m22, term);
}

/**
 * Source follower output impedance.
 *
 * The output impedance of a source follower is:
 *   Rout = 1/(gm + gmb) || rs || ro
 *
 * For typical values: gm = 1mS, gmb = 0.2mS, ro = 50kΩ, rs = 10kΩ:
 *   Rout = 1/1.2mS || 10kΩ || 50kΩ = 833Ω || 10kΩ || 50kΩ ≈ 770Ω
 *
 * The dominant term is 1/gm. The body effect (gmb) reduces Rout further,
 * which is beneficial. ro and rs have minor effect.
 *
 * Course: Berkeley EE140 — Output impedance of followers
 */
double gparams_source_follower_rout(double gm, double gmb, double rs) {
    double g_total = gm + gmb;
    if (g_total < 1e-30) return INFINITY;

    double rout_gm = 1.0 / g_total;
    if (rs < 1e-30) return rout_gm;

    /* Parallel combination of rout_gm and rs */
    return (rout_gm * rs) / (rout_gm + rs);
}

/**
 * Intrinsic gain: A_int = |g21(open circuit)| = gm * ro.
 *
 * This is the maximum achievable voltage gain from a single transistor
 * with an ideal current-source load.
 *
 * Historical values (typical NMOS):
 *   1970s (10µm): gm*ro ≈ 50-200
 *   1990s (1µm):  gm*ro ≈ 30-100
 *   2000s (180nm): gm*ro ≈ 20-40
 *   2010s (28nm):  gm*ro ≈ 10-20
 *   2020s (5nm):   gm*ro ≈ 3-8
 *
 * The decline is due to: shorter channels → worse channel-length
 * modulation (lower ro) + velocity saturation (lower gm).
 * This is why cascoding and gain-boosting are essential in modern CMOS.
 */
double gparams_intrinsic_gain(matrix2x2_t g) {
    return complex_mag(g.m21);
}
