#ifndef AC_ANALYSIS_H
#define AC_ANALYSIS_H
#include "circuit_elements.h"
#include <complex.h>
double complex cpx_from_polar(double magnitude, double phase_deg);
double cpx_magnitude(double complex z);
double cpx_phase_deg(double complex z);
double cpx_phase_rad(double complex z);
double complex cpx_conjugate(double complex z);
double complex ac_impedance_resistor(double R);
double complex ac_impedance_capacitor(double C, double omega);
double complex ac_impedance_inductor(double L, double omega);
double complex ac_impedance_capacitor_real(double C,double omega,double esr,double esl);
double complex ac_impedance_inductor_real(double L,double omega,double dcr,double rc);
double complex ac_impedance_rlc_series(double R,double L,double C,double omega);
double complex ac_impedance_rlc_parallel(double R,double L,double C,double omega);
double complex ac_equivalent_impedance(const Circuit_t *ckt,int n1,int n2,double omega);
int ac_nodal_solve(int n,const double complex *Y,const double complex *I,double complex *V);
int ac_nodal_build_Y(const Circuit_t *ckt,double omega,double complex *Y,double complex *I);
int ac_mesh_solve(int m,const double complex *Z,const double complex *V,double complex *I);
typedef struct { double freq_hz; double magnitude; double phase_deg; } FreqPoint_t;
int freq_response_rc_lowpass(double R,double C,double fs,double fe,int n,FreqPoint_t *r);
int freq_response_rc_highpass(double R,double C,double fs,double fe,int n,FreqPoint_t *r);
typedef enum { FR_RLC_ACROSS_R=0, FR_RLC_ACROSS_L=1, FR_RLC_ACROSS_C=2 } RLC_Output_t;
int freq_response_rlc_series(double R,double L,double C,RLC_Output_t o,double fs,double fe,int n,FreqPoint_t *r);
int freq_response_rlc_parallel(double R,double L,double C,double fs,double fe,int n,FreqPoint_t *r);
typedef struct { double P,Q,S,pf,phi_deg; int leading; } ComplexPower_t;
ComplexPower_t complex_power_from_vi(double Vr,double Vp,double Ir,double Ip);
ComplexPower_t complex_power_from_v_z(double Vr,double complex Z);
ComplexPower_t complex_power_from_i_z(double Ir,double complex Z);
double pf_correction_capacitance(double P,double V,double f,double pf_old,double pf_new);
double pf_correction_unity(double P,double V,double f,double pf_old,int lag);
typedef struct { double f0_hz,omega0,Q,BW_hz,BW_radps,f_lower_hz,f_upper_hz,Z_at_res,zeta; } Resonance_t;
Resonance_t resonance_series_analyze(double R,double L,double C);
Resonance_t resonance_parallel_analyze(double R,double L,double C);
double rc_lowpass_cutoff(double R,double C);
double complex rc_lowpass_h(double R,double C,double complex s);
double rc_lowpass_magnitude(double R,double C,double freq_hz);
double rc_lowpass_phase(double R,double C,double freq_hz);
double rc_highpass_cutoff(double R,double C);
double complex rc_highpass_h(double R,double C,double complex s);
double rc_highpass_magnitude(double R,double C,double freq_hz);
double sallen_key_lp_cutoff(double R1,double R2,double C1,double C2);
double sallen_key_lp_q(double R1,double R2,double C1,double C2);
double complex sallen_key_lp_h(double R1,double R2,double C1,double C2,double complex s);
double sallen_key_hp_cutoff(double R1,double R2,double C1,double C2);
double bp_center_freq(double L,double C);
double bp_bandwidth(double R,double L);
double bp_quality(double f0,double bw);
double notch_attenuation_db(double R,double L,double C,double freq_hz);
int bode_compute(const double *b,int m,const double *a,int n,double fs,double fe,int np,double *mag,double *ph);
int bode_single_pole(double fp,double fs,double fe,int np,double *mag,double *ph);
int bode_single_zero(double fz,double fs,double fe,int np,double *mag,double *ph);
int bode_complex_poles(double wn,double z,double fs,double fe,int np,double *mag,double *ph);
typedef enum { MATCH_LP=0, MATCH_HP=1 } MatchType_t;
typedef struct { double L_henries,C_farads; MatchType_t type; int valid; } ImpedanceMatch_t;
ImpedanceMatch_t impedance_match_l_network(double Rs,double Rl,double f);
typedef struct { double C1,C2,L; int valid; } PiMatch_t;
PiMatch_t impedance_match_pi_network(double Rs,double Rl,double f,double Q);
typedef struct { double L1,L2,C; int valid; } TMatch_t;
TMatch_t impedance_match_t_network(double Rs,double Rl,double f,double Q);
double complex reflection_coefficient(double complex ZL,double Z0);
double return_loss_db(double complex ZL,double Z0);
double vswr(double complex ZL,double Z0);
double mismatch_loss_db(double complex ZL,double Z0);
double unilateral_transducer_gain(double s21,double s11,double s22,double complex gs,double complex gl);
double rollett_stability_k(double s11,double s12,double s21,double s22);
double stability_delta_mag(double complex s11,double complex s12,double complex s21,double complex s22);
double cascaded_noise_figure_linear(const double *nf,const double *g,int n);
double cascaded_noise_figure_db(const double *nf,const double *g,int n);
double db_to_linear(double db);
double linear_to_db(double linear);
double p1db_from_psat(double p_sat_dbm);
double iip3_from_two_tone(double pin,double dp);
double oip3_from_iip3(double iip3,double g);
#endif
