#ifndef DC_ANALYSIS_H
#define DC_ANALYSIS_H
#include "circuit_elements.h"
double ohm_law_voltage(double I_amps, double R_ohms);
double ohm_law_current(double V_volts, double R_ohms);
double ohm_law_resistance(double V_volts, double I_amps);
double joule_power_from_vi(double V_volts, double I_amps);
double joule_power_from_ir(double I_amps, double R_ohms);
double joule_power_from_vr(double V_volts, double R_ohms);
double conductance_from_resistance(double R_ohms);
double resistance_from_conductance(double G_siemens);
double kcl_residual(const double *currents, int n);
double kvl_residual(const double *voltages, int n);
double voltage_divider(double V_in, double R1, double R2);
int voltage_divider_n(double V_in, const double *R, double *V_out, int n);
double current_divider_2r(double I_total, double R_other, double R_this);
int current_divider_n(double I_total, const double *R, double *I_out, int n);
double resistance_series(const double *R, int n);
double resistance_parallel_2(double R1, double R2);
double resistance_parallel(const double *R, int n);
double capacitance_series(const double *C, int n);
double capacitance_parallel(const double *C, int n);
double inductance_series(const double *L, int n);
double inductance_parallel(const double *L, int n);
int nodal_analysis_solve(int n, const double *G, const double *I, double *V);
int nodal_build_conductance(const Circuit_t *ckt, double *G, double *I);
int mesh_analysis_solve(int m, const double *R, const double *V, double *I_mesh);
int mesh_build_resistance(const Circuit_t *ckt, double *R_mat, double *V_vec);
typedef struct { double V_th; double R_th; } TheveninEquiv_t;
TheveninEquiv_t thevenin_from_oc_sc(double V_oc, double I_sc);
TheveninEquiv_t thevenin_from_voc_rth(double V_oc, double R_th);
typedef struct { double I_n; double R_n; } NortonEquiv_t;
NortonEquiv_t norton_from_sc_oc(double I_sc, double V_oc);
NortonEquiv_t thevenin_to_norton(TheveninEquiv_t th);
TheveninEquiv_t norton_to_thevenin(NortonEquiv_t no);
double max_power_transfer_load_r(double R_th);
double max_power_transfer_pmax(double V_th, double R_th);
double load_power(double V_th, double R_th, double R_load);
double load_efficiency(double R_th, double R_load);
double max_power_efficiency(void);
int superposition_solve(const Circuit_t *ckt, double *V_nodes, int n_nodes);
void delta_to_wye(double Ra,double Rb,double Rc,double *R1,double *R2,double *R3);
void wye_to_delta(double R1,double R2,double R3,double *Ra,double *Rb,double *Rc);
double wheatstone_bridge_vout(double Vin,double R1,double R2,double R3,double Rx);
double wheatstone_bridge_rx_balanced(double R1,double R2,double R3);
int wheatstone_is_balanced(double R1,double R2,double R3,double Rx,double tol);
int dc_operating_point(const Circuit_t *ckt,double *V,double *I);
double tellegen_power_sum(const Circuit_t *ckt,const double *v,const double *i);
int reciprocity_verify(const Circuit_t *ckt,int a1,int a2,int b1,int b2,double *r);
typedef struct { double z11,z12,z21,z22; } ZParams_t;
typedef struct { double y11,y12,y21,y22; } YParams_t;
typedef struct { double h11,h12,h21,h22; } HParams_t;
YParams_t z_to_y_params(ZParams_t z);
ZParams_t y_to_z_params(YParams_t y);
HParams_t z_to_h_params(ZParams_t z);
ZParams_t h_to_z_params(HParams_t h);
double terminal_voltage(double V_oc,double I_load,double R_int);
double internal_resistance(double V_oc,double V_load,double I_load);
double loading_effect_voltage(double V_actual,double R_source,double R_meter);
double potentiometer_output(double V_in,double R_fraction);
#endif
